### ISSUE TITLE
Issues with Editing Records

### ISSUE THREAD

**Issue by AUSROGER** [anjosh/htm-project#52] opened 2019-04-05 21:21 UTC
If a phone number is entered without an initial "1" then it is not displaying correctly on the Profile Detail page.
If I edit that record and save it then the system is appending an additional "1" to the front of the Phone number each time it is saved thus corrupting the number.

**Comment by AUSROGER** [comment] 2019-04-05 21:25
![3rd save after edit.JPG](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/e16ece87-1092-4101-bdfd-f19dc1fe4bfc)!

[First Save after edit.JPG](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/d3b890c3-cda5-48ba-8a78-16639bde351b)

**Comment by AUSROGER** [comment] 2019-04-05 21:26
Also - Male Female Selection is not saving. This should be updated when importing the spreadsheet based on whether the name is in the Husband or Wife column

**Comment by anjosh** [comment] 2019-04-08 00:54
Thanks for reporting Roger!

**Comment by anjosh** [comment] 2019-04-08 01:06
@AUSROGER I'm not able to reproduce the first issue. Could you explain in more details the steps you took to make it happen?

**Comment by anjosh** [comment] 2019-04-08 14:50
I created #55 to track fixing the issues with male and female.

**Comment by AUSROGER** [comment] 2019-04-08 18:38
Here is a link to a video of the problem I am having with saving phone numbers
https://drive.google.com/open?id=1SfrmgHM-lGY_456MadnzK3p0OjugEBNV
This also demonstrates how the Male / Female settings are not being updated either

**Comment by AUSROGER** [comment] 2019-04-08 18:40
I have uploaded a video to show the problem.
Also, I do not seem to have privileges to mark bugs as resolved or move items around on the KanBan board. Could you look into that please

Roger Wetherall | M 203-260-2279
wetherallroger@gmail.com

**Comment by anjosh** [comment] 2019-04-10 16:34
Thanks for the video! I sent you an email to invite you to the Zenhub workspace. I hope that fixes that issue.

**Comment by anjosh** [comment] 2019-04-10 17:42
That video explains the problem perfectly. I should be able to fix it now thanks!

**Comment by anjosh** [comment] 2019-04-10 20:23
both phone number and gender issues should be fixed now

**Comment by AUSROGER** [comment] 2019-04-11 14:23
Reviewed the bug and confirmed that it is fixed now

**Comment by anjosh** [comment] 2019-04-12 16:21
Thank you!

**Closed** 2019-09-17 17:13 UTC
Labels: bug
